apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
  labels:
    app: my-flask-app
spec:
  type: NodePort
  ports:
  - name: main-port
    port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 20001
  selector:
    app: my-flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  labels:
    app: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 5
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: IMAGE-my-flask-app:VERSIONTAG
        imagePullPolicy: Always
      nodeSelector:
         group: "flask"
---
