apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    app: mysql-master
spec:
  type: NodePort
  ports:
  - name: main-port
    port: 3306
    targetPort: 3306
    protocol: TCP
    nodePort: 20002
  selector:
    app: mysql-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master
  labels:
    app: mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-master
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 5
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
      - name: mysql-masters
        image: mysql-master:0.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        - name: MYSQL_REPLICATION_USER
          value: 'admin'
        - name: MYSQL_REPLICATION_PASSWORD
          value: 'admin'
        imagePullPolicy: Always
      nodeSelector:
         group: "mysqlmaster"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-slave
  labels:
    app: mysql-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 5
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      containers:
      - name: mysql-slave
        image: mysql-slave:0.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        - name: MYSQL_REPLICATION_USER
          value: 'admin'
        - name: MYSQL_REPLICATION_PASSWORD
          value: 'admin'
        imagePullPolicy: Always
      nodeSelector:
         group: "mysqlslave"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    app: mysql-slave
spec:
  type: NodePort
  ports:
  - name: main-port
    port: 3306
    targetPort: 3306
    protocol: TCP
    nodePort: 20003
  selector:
    app: mysql-slave
